### ISSUE TITLE
Does't seem to work on Xcode 5 / iOS 7 SDK

### ISSUE THREAD

**Issue by deberle** [ParsePlatform/OneToManyTutorial#1]
When I try to build the project in Xcode I get this error:

    ld: file is universal (3 slices) but does not contain a(n) armv7s slice: [...]/OneToManyTutorial-master/OneToManyTutorial-iOS/Parse.framework/Parse' for architecture armv7s
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by facebook-github-bot-1** [comment]
Thank you for your patience. After 30 days with no updates from the core team, we're closing out the issue. If you're still experiencing the problem described, please reopen the issue - thanks!
